version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
os: Windows Server 2012 R2
init:
- ps: >-
    Write-Host "Initializing Build Host";


    # iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'));
environment:
  POWERSHELLGALLERY_API_TOKEN:
    secure: a+hx9b2u5fyhuLZSxUL50dedlnWj5PFl4zA7KcsilJxWnEtG6psrcUWUUtXgGzkf
  PUSHBULLET_API_TOKEN:
    secure: 2MwCYfQNYPfPjDqNJ1EL8VrIydQNRz3MfhnuI9dzSZag9JwCnqk5k3mMYTFn4ORk
  PSGetZipUrl:
    secure: +i9sec3Z3A23nH73dr2i4gCrcO+iW89qtunVf/pZ4fWFDRjqp+1/8e+cWdXElW5R
install:
- ps: .\psievm\.appveyor\appveyor.install.ps1
before_build:
- ps: .\psievm\.appveyor\appveyor.before-build.ps1
build:
  project: .\psievm\.build\BuildPSIEVM.msbuild
  verbosity: normal
after_build:
- ps: .\psievm\.appveyor\appveyor.after-build.ps1
test_script:
- ps: .\psievm\.appveyor\appveyor.run-tests.ps1
artifacts:
- path: '**\bin\**\psievm.*.zip'
  name: Zip
- path: '**\bin\**\psievm.*.nupkg'
  name: Nupkg
- path: '**\bin\**\psievm-tests.results.xml'
  name: NUnit
before_deploy:
- ps: .\psievm\.appveyor\appveyor.before-deployment.ps1
deploy:
- provider: GitHub
  tag: $(APPVEYOR_PROJECT_NAME)-v$(CI_BUILD_VERSION)
  release: $(APPVEYOR_PROJECT_NAME)-v$(CI_BUILD_VERSION)
  auth_token:
    secure: UEgy2H9zJKLi599QoO3qVf5BKFqloRQ246ez9cEgsfV3vooAUfVopMS9+IjRtArL
  artifact: Zip
  draft: false
  prerelease: true
  on:
    branch: master
    CI_DEPLOY_GITHUB: True
- provider: NuGet
  server: https://chocolatey.org/
  api_key:
    secure: ct0QuILR4Ewr9Ri7jzYoLXBSAG5Bk2MEIqYP8bO44bEDo5wmQPl0a+qxRKnLFz/U
  skip_symbols: true
  artifact: Nupkg
  on:
    branch: master
    CI_DEPLOY_NUGET: True
after_deploy:
- ps: .\psievm\.appveyor\appveyor.after-deployment.ps1